name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    
jobs:
  my_job:
    container:
      image: mambauser/micromamba:latest
      options: --user=root
    steps:
    - uses: actions/checkout@master
    - shell: _entrypoint.sh /bin/bash --noprofile --norc -eo pipefail {0}
      run: |
        micromamba info
        which micromamba
