name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  OMP_NUM_THREADS: 2
    
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sblauth/docker_mwe:main
      options: --user=root
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Test installation
      shell: _entrypoint.sh /bin/bash --noprofile --norc -eo pipefail {0}
      run: |
        micromamba list
        micromamba info
        which micromamba
        python -c "import numpy"
